In [1]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords

In [2]:

with open("../data/tiny_shakespear.txt", "r") as f:
    text = f.read()

# разобьём текст на части - шаг необязательный, 
# просто искусственно делаем из 1 документа 10 разных)
step = 100000
docs = [text[i:i+step] for i in range(0, len(text), step)]

In [3]:
stop_words = stopwords.words('english')

tf_idf = TfidfVectorizer(stop_words=stop_words) # сразу передадим стоп-слова

# используем комбинацию методов fit и transform
tf_idf_matrix = tf_idf.fit_transform(docs)

In [4]:
print("N_documents x Vocabulary_size:", tf_idf_matrix.shape, '\n')
pd.DataFrame(
    index=['token value','token weight'],
    data=[
          list(pd.Series(tf_idf.get_feature_names_out()[:5]).map(lambda s: s.ljust(7))),   # 5 токенов из словаря
          list(pd.DataFrame(tf_idf_matrix[0, :5].todense()).iloc[0])                       # веса этих 5 токенов
    ]
).T

N_documents x Vocabulary_size: (12, 11319)

  token value token weight
0     abandon          0.0
1     abase            0.0
2     abate            0.0
3     abated      0.003857
4     abbey            0.0

# Задание 2
Постройте матрицу TF-IDF с такими особенностями:
* Ограничьте максимальный размер словаря 10000.
* Используйте стоп-слова и одно+двухсловесные словесные ngram’ы одновременно.
* Ограничьте минимальную частотность слов двумя словами, а долю самых частых слов сверху в 95%.
* Добавьте стоп-слова, а также ограничения из условия в параметры TfidfVectorizer: `ngram_range=(1, 2)`, `min_df=2`, `max_df=0.95`, `max_features=10000`

In [5]:
step = 100000
docs = [text[i:i+step] for i in range(0, len(text), step)]

tf_idf = TfidfVectorizer(analyzer="word",
                         stop_words=stop_words,
                         ngram_range=(1, 2),      # 1-2 словесные n-gramы
                         min_df=2,                # токен не реже, чем в 2 документах
                         max_df=0.95,             # не учитываем токен с встречаемостью > 95%
                         max_features=10000       # размер словаря
)

tf_idf_matrix = tf_idf.fit_transform(docs)

In [6]:
print("N_documents x Vocabular_size:", tf_idf_matrix.shape)
pd.DataFrame(
    index=['token value','token weight'],
    data=[
          list(pd.Series(tf_idf.get_feature_names_out()[:5]).map(lambda s: s.ljust(7))),   # 5 токенов из словаря
          list(pd.DataFrame(tf_idf_matrix[0, :5].todense()).iloc[0])                       # веса этих 5 токенов
    ]
).T

N_documents x Vocabular_size: (12, 10000)

  token value token weight
0     abandon          0.0
1     abate            0.0
2     abhor       0.003615
3     abhorr      0.002599
4    abhorred          0.0